# print("Language", "Greetings")

print("English : ","Hello")
print("Spanish : ","Hola")
print("French : ","Bonjour")
print("Italian : ","Ciao")
print("Chinese : ","Nǐ hǎo")
print("Japanese : ","Konnichiwa")
print("Russian : ","Privet")
print("Filipino : ","Kamusta")
print("Korean : ","Annyeonghaseyo")
print("Vietnamese : ","Xin chào")
print("Korean : ","Annyeonghaseyo")
print("Thai : ","Sawasdee")
